run: Application.jar
	java --module-path "javafx-sdk-15.0.1\lib" --add-modules javafx.controls,javafx.fxml,javafx.web -jar "Application.jar"

test: project-four-final.jar
	java --module-path "javafx-sdk-15.0.1\lib" --add-modules javafx.controls,javafx.fxml,javafx.web -jar "project-four-final.jar"


compile:
	@echo javac --module-path JavaFXForLinux/ --add-modules javafx.controls,javafx.fxml,javafx.web Main.java

