run: Application.jar
	java --module-path "C:\Program Files\JavaFX\javafx-sdk-15.0.1\lib" --add-modules javafx.controls,javafx.fxml,javafx.web -jar "C:\Users\Taylor\IdeaProjects\project-four-final\out\artifacts\Application_jar/Application.jar"

compile: Main.class

Main.class: Main.java
	javac --module-path JavaFXForLinux/ --add-modules javafx.controls,javafx.fxml,javafx.web Main.java

test: project-four-final.jar
	java --module-path "C:\Program Files\JavaFX\javafx-sdk-15.0.1\lib" --add-modules javafx.controls,javafx.fxml,javafx.web -jar "C:\Users\Taylor\IdeaProjects\project-four-final\out\artifacts\Application_jar/project-four-final.jar"

clean:
	rm Main.class